version: '3.3'
services:
  nginx:
    image: "nginx:1.12.2"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/cert/domain.crt:/etc/nginx/cert/domain.crt:ro
    - ./nginx/cert/domain.key:/etc/nginx/cert/domain.key:ro
    ports:
    - 8443:443
    networks:
      nw:
        aliases:
        - secure.internal
  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nginx
    networks:
      nw:

networks:
  nw:
    driver: bridge

